apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bloo-graph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bloo-graph
    spec:
      containers:
      - name: bloo-graph
        image: gcr.io/bloo-cloud/bloo-graph:latest
        imagePullPolicy: "Always"
        env:
          - name: REF_DB_HOST
            value: bloo-refdb
          - name: REF_DB_USERNAME
            value: bloo
          - name: REF_DB_PASSWORD
            value: WxQDjscW7gCrHgXy22JS5BaK6yR65SmYXzwmXUmdcUfpHZd98Nj2qW6WwBVwFGKh
          - name: REF_DB_NAME
            value: bloo
          - name: JWT_SECRET
            value: Y2JNaFBBOXZVYnFxOFJ6cm00S3ZkQk51U0Y1ZkFNTlhHUWM5ZjdOdXM4SnQ0OExER1RtUTlXSmFyUUpYYUpTYUpXZlRFcVdXd3JDNVZKU2R1RnFjMlZDYm1GZm5SZTJaVENyMnpjdGdHMkNBSGI0Y2F2dHByejVWNGtDajJDc3d2cjZoUnBERTI4d3I5dlE2clZtM1JNWm0zbVN4cFpCSFBkN1ZocGVjUmVQUlQ3VG5aZFZQVThVZG5ZZHc1ejZ0RjVocDRKYUdHMjdUdTRDUHhSNndMZngyenE5ekhMdFRBU213U3VSanFVZmNhUXE0RDl1NVJzSFpTamFjVkR6OQ==
          - name: JWT_REFRESH_SECRET
            value: eG1Kakg4VHp2YzdQZ3Q5RlJYTEUycnZ4SlkzTVRwQlhqQlBNU0hCTVVWRVFTU1d4RzZKQmJaTHRhelMyNXZlZWNIRVFoTnI4SGRMWVhSNDZzVTRHVFB1alZFY1pIOHU0aFF2RFAzeUZnald1VXp5ZnFOUGF4eGpxeEJ4VUhmeW10ZVROZXc5dWRYVnpibUZtVFFBWUhBQkoyS3Q0RmVNZVFyU3FOQ3NreHU1cnhhRUMyS0tKdUFyRFhCQmZCN3dWcG5OWEN3QmdNSGJRcnVLYjhxdnd0Z0pjS1ZuNndwdGZRVkd5eUprWDNKWVlTclRFOVNIUnFhRVc2TnJEY1lDTg==
          - name: NODE_ENV
            value: production
        ports:
        - containerPort: 4000
