apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: bloo-ssl-production
spec:
  acme:
    email: ops@bloo.co
    http01: {}
    privateKeySecretRef:
      key: ""
      name: bloo-ssl-production
    server: https://acme-v02.api.letsencrypt.org/directory
